changelog:
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Docs
      labels:
        - docs
    - title: Maintenance
      labels:
        - chore
        - ci
        - refactor
  exclude:
    labels:
      - skip-changelog
